### PR TITLE
Fix #96: Remove old catch

### LINKED ISSUE #96: ktn_dodger usage of 'catch ...' is deprecated (Erlang R29)
Using Erlang R29 generates the following warning:
```
===> Compiling _build/default/plugins/katana_code/src/ktn_dodger.erl failed
     _build/default/plugins/katana_code/src/ktn_dodger.erl:

 390       case catch {ok, Parser(Ts, Opt)} of
                 'catch ...' is deprecated and will be removed in a
future version of Erlang/OTP; please use 'try ... catch ... end' instead.
```

### PR DESCRIPTION
**Pull request by elbrujohalcon**
Removal of old-style `catch`, plus plugin updates.

### CODE REVIEW

File: src/ktn_dodger.erl [hunk 1]
```diff
@@ -96,6 +96,12 @@
 %% The following should be: 1) pseudo-uniquely identifiable, and 2)
 %% cause nice looking error messages when the parser has to give up.
 
+%% We use some very weird macros here, because this module was copied from epp_dodger
+-elvis([{elvis_style, macro_naming_convention, disable}]).
+
+%% PreFix is not the same as Prefix
```
Comment (paulo-ferraz-oliveira) [inline src/ktn_dodger.erl:102]: They got to us... hide, hide!

File: src/ktn_dodger.erl [hunk 2]
```diff
@@ -380,22 +386,23 @@ extract_escript_header(_) ->
...
 parse_form(Parser, Ts, L1, NoFail, Opt) ->
-    case catch {ok, Parser(Ts, Opt)} of
-        {'EXIT', Term} ->
-            {error, io_error(L1, {unknown, Term}), L1};
-        {error, Term} ->
+    try Parser(Ts, Opt) of
+        F ->
+            {ok, F, L1}
+    catch
+        throw:{error, Term} ->
```
Comment (paulo-ferraz-oliveira) [inline src/ktn_dodger.erl:393]: Who consumes these?

**Review by paulo-ferraz-oliveira — APPROVED** [review]

File: src/ktn_dodger.erl (hunk 2 above)
Comment (elbrujohalcon) [reply src/ktn_dodger.erl]: Hank… I believe.

Comment (paulo-ferraz-oliveira) [reply src/ktn_dodger.erl:393]: In any case, who consumes these? Is this an internal `throw` alone?
